#!/bin/bash

C_FLAGS="-Wnested-externs -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wdeclaration-after-statement -Werror-implicit-function-declaration -Wno-deprecated-declarations -fno-strict-aliasing -Wno-cast-function-type -Wwrite-strings -Wundef -Wredundant-decls -Wpointer-arith -Wmissing-noreturn -Wmissing-declarations -Winit-self -Wformat-security -Wformat  -fPIE   -pthread -I/usr/include/libsecret-1 -I/usr/include/libsoup-2.4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/nss -I/usr/include/nspr -DLIBICAL_GLIB_UNSTABLE_API=1 -I/usr/include/gio-unix-2.0 -I/usr/include/gcr-3 -I/usr/include/gck-1 -I/usr/include/p11-kit-1 -I/usr/include/json-glib-1.0 -I/usr/include/libgdata -I/usr/include/goa-1.0 -I/usr/lib/x86_64-linux-gnu/goa-1.0/include -isystem /usr/include/mit-krb5"

C_DEFINES="-DEDS_TEST_ADDRESS_BOOK_DIR=\"/usr/src/evolution-data-server-3.38.1/build/src/addressbook/backends/file\" -DEDS_TEST_CALENDAR_DIR=\"/usr/src/evolution-data-server-3.38.1/build/src/calendar/backends/file\" -DEDS_TEST_CAMEL_DIR=\"/usr/src/evolution-data-server-3.38.1/build/src/camel/providers/local\" -DEDS_TEST_DBUS_SERVICE_DIR=\"/usr/src/evolution-data-server-3.38.1/build/tests/test-server-utils/services\" -DEDS_TEST_REGISTRY_DIR=\"/usr/src/evolution-data-server-3.38.1/build/src/modules/cache-reaper\" -DEDS_TEST_SCHEMA_DIR=\"/usr/src/evolution-data-server-3.38.1/build/data\" -DEDS_TEST_SUBPROCESS_BOOK_PATH=\"/usr/src/evolution-data-server-3.38.1/build/src/addressbook/libedata-book/evolution-addressbook-factory-subprocess\" -DEDS_TEST_SUBPROCESS_CAL_PATH=\"/usr/src/evolution-data-server-3.38.1/build/src/calendar/libedata-cal/evolution-calendar-factory-subprocess\" -DEDS_TEST_TOP_BUILD_DIR=\"/usr/src/evolution-data-server-3.38.1/build/src\" -DEDS_TEST_WORK_DIR=\"/usr/src/evolution-data-server-3.38.1/build/tests/test-server-utils/cache\" -DGDK_VERSION_MAX_ALLOWED=GDK_VERSION_3_10 -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_10 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_46 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_46 -DG_LOG_DOMAIN=\"test-fixture\" -DINSTALLED_TEST_DIR=\"/usr/local/libexec/evolution-data-server/installed-tests\" -DLDAP_DEPRECATED -DSOUP_VERSION_MAX_ALLOWED=SOUP_VERSION_2_58 -DSOUP_VERSION_MIN_REQUIRED=SOUP_VERSION_2_58 -DSRCDIR=\"/usr/src/evolution-data-server-3.38.1/tests/test-server-utils\" -D_LARGEFILE64_SOURCE=1"

C_INCLUDES="-I/usr/src/evolution-data-server-3.38.1/build -I/usr/src/evolution-data-server-3.38.1/build/src -I/usr/src/evolution-data-server-3.38.1/build/tests/test-server-utils -I/usr/src/evolution-data-server-3.38.1/src -I/usr/src/evolution-data-server-3.38.1/tests/test-server-utils -I/usr/include/libsecret-1 -I/usr/include/libsoup-2.4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/nss -I/usr/include/nspr -I/usr/include/gio-unix-2.0 -I/usr/src/evolution-data-server-3.38.1/build/src/private -I/usr/src/evolution-data-server-3.38.1/src/private -I/usr/src/evolution-data-server-3.38.1/build/src/libedataserver -I/usr/include/gcr-3 -I/usr/include/gck-1 -I/usr/include/p11-kit-1 -I/usr/include/json-glib-1.0 -I/usr/include/libgdata -I/usr/include/goa-1.0 -I/usr/lib/x86_64-linux-gnu/goa-1.0/include -I/usr/src/evolution-data-server-3.38.1/build/src/camel -I/usr/src/evolution-data-server-3.38.1/src/camel -I/usr/src/evolution-data-server-3.38.1/build/src/addressbook -I/usr/src/evolution-data-server-3.38.1/src/addressbook -I/usr/src/evolution-data-server-3.38.1/build/src/addressbook/libebook -I/usr/src/evolution-data-server-3.38.1/build/src/libebackend -I/usr/src/evolution-data-server-3.38.1/build/src/addressbook/libebook-contacts -I/usr/src/evolution-data-server-3.38.1/build/src/addressbook/libedata-book -I/usr/src/evolution-data-server-3.38.1/build/src/calendar -I/usr/src/evolution-data-server-3.38.1/src/calendar -I/usr/src/evolution-data-server-3.38.1/build/src/calendar/libecal"

gcc -g -fPIC -shared e-test-server-utils.c -o e-test-utils.so $C_DEFINES $C_FLAGS $C_INCLUDES  `pkg-config --libs libecal-2.0` `pkg-config --libs libebook-1.2` `pkg-config --libs libsoup-2.4`
install e-test-utils.so ../resources/lib/x86_64/linux/
